- name: Install nginx on the nodes
  hosts: all
  become: yes

  tasks:
    - name: nginx for CentOS
      include_tasks: CentOS.yml
      #when: ansible_distribution == 'CentOS'
      # Amazon Linux2 를 사용하므로 facts 변수로는 Amazon 으로 써야 함
      when: ansible_distribution == 'Amazon'

    
    - name: nginx for Ubuntu
      include_tasks: Ubuntu.yml
      when: ansible_distribution == 'Ubuntu'


